export interface CarData {
  id: string
  brand: string
  model: string
  year: number
  color: string
  mileage: number
  fuelType: string
  transmission: string
  seats: number
  condition: string
  price: number
  deposit?: number
  monthlyInstallment?: number
  remainingMonths?: number
  remainingBalance?: number
  bankName?: string
  location: string
  city: string
  description: string
  features: string[]
  photos: string[]
  featured: boolean
  type: 'rent' | 'sale' | 'auction' | 'continueLoan'
  dealerName: string
  dealerId: string
  dealerVerified: boolean
  rating: number
  vehicleCondition?: string
  requiredDocs?: string[]
  auctionEnd?: string
  auctionStartBid?: number
  currentBid?: number
}

export interface DealerData {
  id: string
  companyName: string
  logo: string
  city: string
  verified: boolean
  rating: number
  totalListings: number
  specialization: string[]
}

const carPhotos = [
  'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
  'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
  'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',
  'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
  'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
  'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&q=80',
  'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
  'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80',
  'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80',
  'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
  'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?w=800&q=80',
  'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80',
]

export const sampleCars: CarData[] = [
  {
    id: '1',
    brand: 'BMW',
    model: 'M4 Competition',
    year: 2023,
    color: 'Alpine White',
    mileage: 12000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 4,
    condition: 'certified',
    price: 680,
    deposit: 0,
    location: 'KLCC, Kuala Lumpur',
    city: 'Kuala Lumpur',
    description: 'Experience the thrill of the BMW M4 Competition. Twin-turbo inline-6 with 503hp, M Sport exhaust, and adaptive M suspension. Perfect for those who demand performance and luxury.',
    features: ['M Sport Package', 'Harman Kardon Sound', 'Head-Up Display', 'Adaptive LED', 'M Carbon Bucket Seats', 'Launch Control'],
    photos: [carPhotos[0], carPhotos[1]],
    featured: true,
    type: 'rent',
    dealerName: 'Prestige Auto KL',
    dealerId: 'd1',
    dealerVerified: true,
    rating: 4.9,
  },
  {
    id: '2',
    brand: 'Mercedes-Benz',
    model: 'S-Class S580',
    year: 2024,
    color: 'Obsidian Black',
    mileage: 5000,
    fuelType: 'hybrid',
    transmission: 'auto',
    seats: 5,
    condition: 'new',
    price: 898000,
    location: 'Bangsar, Kuala Lumpur',
    city: 'Kuala Lumpur',
    description: 'The pinnacle of luxury sedans. The S580 features a 4.0L V8 biturbo with EQ Boost, MBUX Hyperscreen, and executive rear seating. Commission your masterpiece today.',
    features: ['MBUX Hyperscreen', 'Burmester 4D Sound', 'Executive Rear Seats', 'Air Balance', '360° Camera', 'Digital Light'],
    photos: [carPhotos[2], carPhotos[3]],
    featured: true,
    type: 'sale',
    dealerName: 'Merc Gallery MY',
    dealerId: 'd2',
    dealerVerified: true,
    rating: 4.8,
  },
  {
    id: '3',
    brand: 'Porsche',
    model: '911 Turbo S',
    year: 2023,
    color: 'GT Silver Metallic',
    mileage: 8000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 2,
    condition: 'certified',
    price: 1200,
    deposit: 5000,
    location: 'Petaling Jaya',
    city: 'Selangor',
    description: 'The ultimate expression of Porsche performance. 640hp twin-turbo flat-six, 0-100 in 2.7 seconds. Available for daily or weekly rental.',
    features: ['Sport Chrono Package', 'PASM', 'Ceramic Brakes', 'Sport Exhaust', 'Porsche Communication Management', 'LED Matrix Lights'],
    photos: [carPhotos[4], carPhotos[5]],
    featured: true,
    type: 'rent',
    dealerName: 'Stuttgart Motors',
    dealerId: 'd3',
    dealerVerified: true,
    rating: 5.0,
  },
  {
    id: '4',
    brand: 'Toyota',
    model: 'Camry 2.5V',
    year: 2022,
    color: 'Phantom Grey',
    mileage: 35000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 5,
    condition: 'used',
    price: 138000,
    location: 'Johor Bahru',
    city: 'Johor',
    description: 'Well-maintained Toyota Camry 2.5V with full service history. Reliable, comfortable, and fuel-efficient. One owner, accident-free.',
    features: ['Toyota Safety Sense', 'Leather Seats', 'Sunroof', 'JBL Sound System', 'Dual Zone Climate', 'Smart Entry'],
    photos: [carPhotos[6], carPhotos[7]],
    featured: false,
    type: 'sale',
    dealerName: 'Southern Auto Hub',
    dealerId: 'd4',
    dealerVerified: true,
    rating: 4.5,
  },
  {
    id: '5',
    brand: 'Honda',
    model: 'Civic Type R',
    year: 2023,
    color: 'Championship White',
    mileage: 15000,
    fuelType: 'petrol',
    transmission: 'manual',
    seats: 5,
    condition: 'certified',
    price: 380,
    deposit: 1000,
    location: 'Cyberjaya',
    city: 'Selangor',
    description: 'The hottest hatchback returns! 315hp VTEC turbo with 6-speed manual. Track-ready with daily drivability. Available for weekend specials.',
    features: ['Brembo Brakes', 'Adaptive Damper System', 'Rev Match Control', 'Honda Sensing', 'Bose Premium Audio', 'Limited Slip Diff'],
    photos: [carPhotos[8], carPhotos[9]],
    featured: true,
    type: 'rent',
    dealerName: 'Honda Power Zone',
    dealerId: 'd5',
    dealerVerified: true,
    rating: 4.7,
  },
  {
    id: '6',
    brand: 'Perodua',
    model: 'Myvi 1.5 AV',
    year: 2023,
    color: 'Granite Grey',
    mileage: 20000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 5,
    condition: 'used',
    price: 52000,
    monthlyInstallment: 698,
    remainingMonths: 60,
    remainingBalance: 41880,
    bankName: 'Maybank',
    deposit: 3000,
    location: 'Shah Alam',
    city: 'Selangor',
    description: 'Continue loan available for this well-maintained Perodua Myvi 1.5 AV. Low mileage, full service record, accident-free. Takeover with easy bank approval.',
    features: ['ASA 3.0 Safety', 'LED Headlamps', 'Smart Infotainment', 'Push Start Button', 'LED DRL', '9" Touchscreen'],
    photos: [carPhotos[10], carPhotos[11]],
    featured: false,
    type: 'continueLoan',
    dealerName: 'MyviMart Shah Alam',
    dealerId: 'd6',
    dealerVerified: true,
    rating: 4.3,
    vehicleCondition: 'Excellent — No scratches, no dents, full service history at Perodua SC',
    requiredDocs: ['IC (MyKad)', '3 months payslip', 'Bank statement (3 months)', 'EPF statement', 'Utility bill', 'Driving license'],
  },
  {
    id: '7',
    brand: 'BMW',
    model: 'X5 xDrive40i',
    year: 2022,
    color: 'Carbon Black',
    mileage: 28000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 7,
    condition: 'used',
    price: 298000,
    monthlyInstallment: 3200,
    remainingMonths: 48,
    remainingBalance: 153600,
    bankName: 'CIMB',
    deposit: 15000,
    location: 'Damansara Heights',
    city: 'Kuala Lumpur',
    description: 'Premium BMW X5 available for continue loan. M Sport package, panoramic roof, and full BMW ConnectedDrive. Well-maintained by single owner.',
    features: ['M Sport Package', 'Panoramic Roof', 'BMW Live Cockpit', 'Driving Assistant Professional', 'Comfort Access', 'Harman Kardon'],
    photos: [carPhotos[1], carPhotos[3]],
    featured: true,
    type: 'continueLoan',
    dealerName: 'Bavarian Motors KL',
    dealerId: 'd7',
    dealerVerified: true,
    rating: 4.8,
    vehicleCondition: 'Very Good — Minor wear on driver seat, otherwise pristine',
    requiredDocs: ['IC (MyKad)', '3 months payslip', 'Bank statement (3 months)', 'EPF statement', 'Utility bill', 'Driving license', 'Employment letter'],
  },
  {
    id: '8',
    brand: 'Lamborghini',
    model: 'Huracán EVO',
    year: 2021,
    color: 'Verde Mantis',
    mileage: 6000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 2,
    condition: 'certified',
    price: 880000,
    auctionStartBid: 750000,
    currentBid: 810000,
    auctionEnd: '2026-06-15T18:00:00Z',
    location: 'Mont Kiara',
    city: 'Kuala Lumpur',
    description: 'Rare opportunity to own a Lamborghini Huracán EVO in striking Verde Mantis. 631hp V10 with LDVI system. Full dealer service history, ceramic brakes, and lifting system.',
    features: ['LDVI System', 'Carbon Ceramic Brakes', 'Lifting System', 'ALA 2.0 Aero', 'Bang & Olufsen', 'Full LED Lighting'],
    photos: [carPhotos[5], carPhotos[4]],
    featured: true,
    type: 'auction',
    dealerName: 'Supercars Asia',
    dealerId: 'd8',
    dealerVerified: true,
    rating: 4.9,
  },
  {
    id: '9',
    brand: 'Proton',
    model: 'X70 Executive',
    year: 2022,
    color: 'Snow White',
    mileage: 42000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 5,
    condition: 'used',
    price: 88000,
    location: 'Penang',
    city: 'Penang',
    description: 'Popular Proton X70 in excellent condition. Full service history, one owner, accident-free. Great value for a premium C-segment SUV.',
    features: ['Proton Safety Suite', 'Panoramic Sunroof', 'Leather Seats', 'GKUI Infotainment', '360° Camera', 'Auto Park Assist'],
    photos: [carPhotos[11], carPhotos[10]],
    featured: false,
    type: 'sale',
    dealerName: 'Proton Elite Penang',
    dealerId: 'd9',
    dealerVerified: true,
    rating: 4.4,
  },
  {
    id: '10',
    brand: 'Mazda',
    model: 'CX-5 Turbo',
    year: 2023,
    color: 'Soul Red Crystal',
    mileage: 18000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 5,
    condition: 'used',
    price: 165000,
    monthlyInstallment: 1850,
    remainingMonths: 54,
    remainingBalance: 99900,
    bankName: 'Hong Leong Bank',
    deposit: 8000,
    location: 'Subang Jaya',
    city: 'Selangor',
    description: 'Stunning Mazda CX-5 Turbo in Soul Red Crystal. Continue loan available with easy approval process. Well-maintained with full service record.',
    features: ['i-Activ AWD', 'Bose Sound', 'Head-Up Display', 'Leather Seats', 'Power Liftgate', 'Apple CarPlay / Android Auto'],
    photos: [carPhotos[7], carPhotos[8]],
    featured: false,
    type: 'continueLoan',
    dealerName: 'Zoom-Zoom Auto',
    dealerId: 'd10',
    dealerVerified: true,
    rating: 4.6,
    vehicleCondition: 'Excellent — Like new, no modifications, original paint',
    requiredDocs: ['IC (MyKad)', '3 months payslip', 'Bank statement (3 months)', 'EPF statement', 'Utility bill', 'Driving license'],
  },
  {
    id: '11',
    brand: 'Audi',
    model: 'RS6 Avant',
    year: 2022,
    color: 'Nardo Grey',
    mileage: 22000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 5,
    condition: 'certified',
    price: 1500,
    deposit: 8000,
    location: 'Kota Kemuning',
    city: 'Selangor',
    description: 'The ultimate super-wagon. 591hp twin-turbo V8, Quattro AWD, and carbon ceramic brakes. Daily usability meets supercar performance.',
    features: ['Quattro AWD', 'Carbon Ceramic Brakes', 'Dynamic Package Plus', 'Matrix LED', 'Bang & Olufsen 3D', 'Air Suspension'],
    photos: [carPhotos[3], carPhotos[0]],
    featured: true,
    type: 'rent',
    dealerName: 'Four Rings Garage',
    dealerId: 'd11',
    dealerVerified: true,
    rating: 4.8,
  },
  {
    id: '12',
    brand: 'Nissan',
    model: 'GT-R NISMO',
    year: 2020,
    color: 'Vibrant Red',
    mileage: 12000,
    fuelType: 'petrol',
    transmission: 'auto',
    seats: 2,
    condition: 'certified',
    price: 1200000,
    auctionStartBid: 980000,
    currentBid: 1050000,
    auctionEnd: '2026-06-20T20:00:00Z',
    location: 'Bukit Jalil',
    city: 'Kuala Lumpur',
    description: 'Legendary Godzilla. GT-R NISMO with 600hp hand-assembled VR38DETT. NISMO-tuned suspension, carbon fibre aero, and race-bred engineering.',
    features: ['NISMO Suspension', 'Carbon Fibre Aero', 'Rays Forged Wheels', 'NISMO Exhaust', 'Brembo Brakes', 'Track Package'],
    photos: [carPhotos[9], carPhotos[6]],
    featured: true,
    type: 'auction',
    dealerName: 'JDM Legends MY',
    dealerId: 'd12',
    dealerVerified: true,
    rating: 4.7,
  },
]

export const sampleDealers: DealerData[] = [
  { id: 'd1', companyName: 'Prestige Auto KL', logo: '🏎️', city: 'Kuala Lumpur', verified: true, rating: 4.9, totalListings: 45, specialization: ['Luxury Rentals', 'European Cars'] },
  { id: 'd2', companyName: 'Merc Gallery MY', logo: '⭐', city: 'Kuala Lumpur', verified: true, rating: 4.8, totalListings: 38, specialization: ['Mercedes-Benz', 'New & Used'] },
  { id: 'd3', companyName: 'Stuttgart Motors', logo: '🏁', city: 'Selangor', verified: true, rating: 5.0, totalListings: 22, specialization: ['Porsche', 'Sports Cars'] },
  { id: 'd4', companyName: 'Southern Auto Hub', logo: '🚗', city: 'Johor', verified: true, rating: 4.5, totalListings: 120, specialization: ['Japanese Cars', 'Budget Friendly'] },
  { id: 'd5', companyName: 'Honda Power Zone', logo: '⚡', city: 'Selangor', verified: true, rating: 4.7, totalListings: 65, specialization: ['Honda', 'Type R Specialist'] },
  { id: 'd6', companyName: 'MyviMart Shah Alam', logo: '🏪', city: 'Selangor', verified: true, rating: 4.3, totalListings: 90, specialization: ['Perodua', 'Continue Loan'] },
  { id: 'd7', companyName: 'Bavarian Motors KL', logo: '🔷', city: 'Kuala Lumpur', verified: true, rating: 4.8, totalListings: 35, specialization: ['BMW', 'Premium Used'] },
  { id: 'd8', companyName: 'Supercars Asia', logo: '🏎️', city: 'Kuala Lumpur', verified: true, rating: 4.9, totalListings: 15, specialization: ['Supercars', 'Auction'] },
]

export const cities = [
  'All Cities', 'Kuala Lumpur', 'Selangor', 'Penang', 'Johor', 'Melaka', 'Perak', 'Negeri Sembilan', 'Sabah', 'Sarawak'
]

export const brands = [
  'All Brands', 'BMW', 'Mercedes-Benz', 'Porsche', 'Toyota', 'Honda', 'Perodua', 'Proton', 'Mazda', 'Audi', 'Nissan', 'Lamborghini', 'Volvo', 'Volkswagen', 'Hyundai', 'Kia'
]
